# Generated by Django 5.0.6 on 2024-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.AddField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Is finished'),
        ),
    ]
