# Generated by Django 5.0.6 on 2024-10-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_todo_options_todo_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(max_length=50, verbose_name='Название'),
        ),
    ]
